'use strict';
const APPS_SCRIPT_URL='DAN_URL_APPS_SCRIPT_EXEC_VAO_DAY';
const state={categories:[],records:[],logs:[],generatedAt:'',loadedYears:new Set()};
const $=id=>document.getElementById(id);
const num=v=>Number(v||0);
const fmt=v=>new Intl.NumberFormat('vi-VN').format(num(v));
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function isoLocal(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function showLoading(v){$('loading').hidden=!v}
function toast(t,type='success'){const x=$('toast');x.textContent=t;x.className='toast show'+(type==='error'?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.classList.remove('show'),3000)}
function notice(t=''){$('notice').hidden=!t;$('notice').textContent=t}
function status(ok,t){$('statusDot').className='status-dot '+(ok===true?'ok':ok===false?'error':'');$('syncText').textContent=t}
function init(){const now=new Date(),today=isoLocal(now);$('daySelect').value=today;$('fromDate').value=today;$('toDate').value=today;$('monthSelect').value=today.slice(0,7);for(let y=now.getFullYear()-6;y<=now.getFullYear()+3;y++)$('yearSelect').add(new Option(String(y),String(y)));$('yearSelect').value=String(now.getFullYear());$('quarterSelect').value=String(Math.ceil((now.getMonth()+1)/3));$('openSeparate').href=APPS_SCRIPT_URL;bind();togglePeriodFields();applyFilter(true)}
function bind(){$('periodType').addEventListener('change',togglePeriodFields);$('btnApply').addEventListener('click',()=>applyFilter(false));$('btnSync').addEventListener('click',()=>applyFilter(false,true));$('btnExport').addEventListener('click',exportCsv);$('searchInput').addEventListener('input',renderLookup);$('historySearch').addEventListener('input',renderHistory);$('btnAccount').addEventListener('click',openAccountModal);$('btnCloseSync').addEventListener('click',async()=>{closeAccountModal();await applyFilter(false,true)});$('accountFrame').addEventListener('load',()=>$('frameLoading').hidden=true);document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeAccountModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('accountModal').hidden)closeAccountModal()});document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')}))}
function togglePeriodFields(){const t=$('periodType').value;$('dayField').hidden=t!=='day';$('fromField').hidden=t!=='range';$('toField').hidden=t!=='range';$('monthField').hidden=t!=='month';$('quarterField').hidden=t!=='quarter';$('yearField').hidden=!(t==='quarter'||t==='year')}
function openAccountModal(){if(!validScriptUrl()){toast('Hãy dán URL Apps Script /exec vào app.js.','error');return}$('frameLoading').hidden=false;$('accountFrame').src=APPS_SCRIPT_URL+(APPS_SCRIPT_URL.includes('?')?'&':'?')+'embedded=1&t='+Date.now();$('accountModal').hidden=false;document.body.classList.add('modal-open')}
function closeAccountModal(){$('accountModal').hidden=true;$('accountFrame').src='about:blank';document.body.classList.remove('modal-open')}
function validScriptUrl(){return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec(?:\?.*)?$/.test(APPS_SCRIPT_URL)}
function loadJsonp(year){return new Promise((resolve,reject)=>{if(!validScriptUrl())return reject(new Error('Chưa dán URL Apps Script /exec hợp lệ vào app.js.'));const cb='yteCb_'+Date.now()+'_'+Math.floor(Math.random()*1e5),s=document.createElement('script');let done=false;const cleanup=()=>{delete window[cb];s.remove()};const timer=setTimeout(()=>{if(done)return;done=true;cleanup();reject(new Error('Quá thời gian kết nối Apps Script.'))},20000);window[cb]=r=>{if(done)return;done=true;clearTimeout(timer);cleanup();r&&r.success?resolve(r):reject(new Error(r?.message||'Không tải được dữ liệu.'))};s.onerror=()=>{if(done)return;done=true;clearTimeout(timer);cleanup();reject(new Error('Không thể kết nối Apps Script.'))};s.src=APPS_SCRIPT_URL+'?'+new URLSearchParams({action:'data',year:String(year),callback:cb,_:String(Date.now())});document.body.appendChild(s)})}
function selectedRange(){const type=$('periodType').value,year=Number($('yearSelect').value);if(type==='day'){const d=$('daySelect').value;return validateRange({type,label:'ngày '+formatDate(d),from:d,to:d})}if(type==='range'){const from=$('fromDate').value,to=$('toDate').value;return validateRange({type,label:`từ ${formatDate(from)} đến ${formatDate(to)}`,from,to})}if(type==='month'){const m=$('monthSelect').value;if(!m)throw new Error('Hãy chọn tháng.');const [y,mo]=m.split('-').map(Number),last=new Date(y,mo,0).getDate();return{type,label:`tháng ${mo}/${y}`,from:`${y}-${String(mo).padStart(2,'0')}-01`,to:`${y}-${String(mo).padStart(2,'0')}-${last}`}}if(type==='quarter'){const q=Number($('quarterSelect').value),sm=(q-1)*3+1,em=q*3,last=new Date(year,em,0).getDate();return{type,label:`quý ${q}/${year}`,from:`${year}-${String(sm).padStart(2,'0')}-01`,to:`${year}-${String(em).padStart(2,'0')}-${last}`}}return{type,label:`năm ${year}`,from:`${year}-01-01`,to:`${year}-12-31`}}
function validateRange(r){if(!r.from||!r.to)throw new Error('Hãy chọn đầy đủ ngày bắt đầu và ngày kết thúc.');if(r.from>r.to)throw new Error('Từ ngày không được lớn hơn đến ngày.');const days=(new Date(r.to+'T00:00:00')-new Date(r.from+'T00:00:00'))/86400000;if(days>1095)throw new Error('Khoảng tra cứu tối đa là 3 năm.');return r}
function yearsForRange(r){const a=Number(r.from.slice(0,4)),b=Number(r.to.slice(0,4));return Array.from({length:b-a+1},(_,i)=>a+i)}
async function applyFilter(initial=false,force=false){let range;try{range=selectedRange()}catch(e){notice(e.message);toast(e.message,'error');return}showLoading(true);notice('');status(null,'Đang đồng bộ...');try{const years=yearsForRange(range);const need=force?years:years.filter(y=>!state.loadedYears.has(y));if(need.length){const rs=await Promise.all(need.map(loadJsonp));rs.forEach(r=>mergeYearData(r));}renderAll();status(true,'Đã đồng bộ '+(state.generatedAt||''));if(!initial)toast('Đã cập nhật dữ liệu theo bộ lọc.')}catch(e){status(false,'Đồng bộ thất bại');notice(e.message);toast(e.message,'error')}finally{showLoading(false)}}
function mergeYearData(r){const y=Number(r.year);state.records=state.records.filter(x=>Number(x.year)!==y).concat(r.records||[]);state.logs=state.logs.filter(x=>Number((x.date||'').slice(0,4))!==y).concat(r.logs||[]);state.categories=r.categories||state.categories;state.generatedAt=r.generatedAt||state.generatedAt;state.loadedYears.add(y)}
function filteredRecords(){const r=selectedRange();return state.records.filter(x=>x.date>=r.from&&x.date<=r.to)}
function aggregate(records){const m=new Map();records.forEach(x=>m.set(x.code,(m.get(x.code)||0)+num(x.value)));return m}
function displayCategories(){const a=[...state.categories];const pos=Math.max(a.findIndex(x=>x.code==='TAM_THAN_KHONG_BHYT')+1,0);a.splice(pos,0,{code:'TAM_THAN_TONG',name:'Khám tâm thần - Tổng cộng',group:'Tâm thần',unit:'Lượt',derived:true});return a}
function getVal(map,code){if(code==='TAM_THAN_TONG')return num(map.get('TAM_THAN_BHYT'))+num(map.get('TAM_THAN_KHONG_BHYT'));return num(map.get(code))}
function renderAll(){renderDashboard();renderLookup();renderReport();renderHistory()}
function renderDashboard(){const range=selectedRange(),map=aggregate(filteredRecords()),featured=['NOI_TRU','NGOAI_TRU','CHUYEN_VIEN','KHAM_TONG_QUAT'];$('summaryTitle').textContent='Số liệu '+range.label;$('kpiGrid').innerHTML=featured.map(code=>{const c=state.categories.find(x=>x.code===code)||{name:code,unit:''};return `<article class="kpi"><div class="label">${esc(c.name)} <span class="unit">${esc(c.unit)}</span></div><div class="value">${fmt(getVal(map,code))}</div></article>`}).join('');$('summaryTable').innerHTML=tableForMap(map,'Giá trị')}
function tableForMap(map,lastTitle){const cats=displayCategories();return `<table><thead><tr><th>Chỉ tiêu</th><th>Nhóm</th><th>Đơn vị</th><th>${esc(lastTitle)}</th></tr></thead><tbody>${cats.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.group)}</td><td>${esc(c.unit)}</td><td>${fmt(getVal(map,c.code))}</td></tr>`).join('')}</tbody></table>`}
function renderLookup(){const q=$('searchInput').value.trim().toLowerCase(),map=aggregate(filteredRecords()),rows=displayCategories().filter(c=>(c.name+' '+c.group).toLowerCase().includes(q));$('lookupTable').innerHTML=`<table><thead><tr><th>Chỉ tiêu</th><th>Nhóm</th><th>Đơn vị</th><th>${esc(selectedRange().label)}</th></tr></thead><tbody>${rows.length?rows.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.group)}</td><td>${esc(c.unit)}</td><td>${fmt(getVal(map,c.code))}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Không tìm thấy chỉ tiêu phù hợp.</td></tr>'}</tbody></table>`}
function rangeMap(from,to){return aggregate(state.records.filter(x=>x.date>=from&&x.date<=to))}
function renderReport(){const range=selectedRange(),cats=displayCategories();if(range.type==='range'||range.type==='day'){$('reportTitle').textContent='Báo cáo '+range.label;$('reportTable').innerHTML=tableForMap(aggregate(filteredRecords()),range.label);return}const year=Number((range.type==='month'?range.from:$('yearSelect').value).toString().slice(0,4));const months=Array.from({length:12},(_,i)=>{const m=i+1,last=new Date(year,m,0).getDate();return rangeMap(`${year}-${String(m).padStart(2,'0')}-01`,`${year}-${String(m).padStart(2,'0')}-${last}`)});$('reportTitle').textContent='Tổng hợp 12 tháng năm '+year;$('reportTable').innerHTML=`<table><thead><tr><th>Chỉ tiêu</th>${months.map((_,i)=>`<th>T${i+1}</th>`).join('')}<th>Cả năm</th></tr></thead><tbody>${cats.map(c=>`<tr><td>${esc(c.name)}</td>${months.map(m=>`<td>${fmt(getVal(m,c.code))}</td>`).join('')}<td>${fmt(months.reduce((s,m)=>s+getVal(m,c.code),0))}</td></tr>`).join('')}</tbody></table>`}
function renderHistory(){const range=selectedRange(),q=$('historySearch').value.trim().toLowerCase(),rows=state.logs.filter(x=>x.date>=range.from&&x.date<=range.to&&(String(x.account||'')+' '+String(x.name||'')+' '+String(x.action||'')+' '+String(x.content||'')).toLowerCase().includes(q)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('historyList').innerHTML=rows.length?rows.map(x=>`<article class="history-item"><div><strong>${esc(formatDate(x.date))}</strong><small>${esc(x.updatedAt)}</small></div><div><strong>${esc(x.name||x.account||'Không rõ')}</strong><small>${esc(x.account||'')} · ${esc(x.action||'')}</small></div><div>${esc(x.content||'')}</div></article>`).join(''):'<div class="empty">Không có nhật ký trong phạm vi đã chọn.</div>'}
function exportCsv(){let range;try{range=selectedRange()}catch(e){toast(e.message,'error');return}const map=aggregate(filteredRecords()),lines=[['Chỉ tiêu','Nhóm','Đơn vị',range.label],...displayCategories().map(c=>[c.name,c.group,c.unit,getVal(map,c.code)])],csv='﻿'+lines.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`so-lieu-y-te-${range.from}-${range.to}.csv`;a.click();URL.revokeObjectURL(a.href)}
function formatDate(s){if(!s)return'';const p=s.split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:s}
document.addEventListener('DOMContentLoaded',init);
