'use strict';
const APPS_SCRIPT_URL='DAN_LINK_APPS_SCRIPT_EXEC_VAO_DAY';
const state={year:new Date().getFullYear(),categories:[],records:[],logs:[],generatedAt:''};
const $=id=>document.getElementById(id);const num=v=>Number(v||0);const fmt=v=>new Intl.NumberFormat('vi-VN').format(num(v));
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function showLoading(v){$('loading').hidden=!v}function toast(t,type='success'){const x=$('toast');x.textContent=t;x.className='toast show'+(type==='error'?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.classList.remove('show'),2800)}function notice(t=''){$('notice').hidden=!t;$('notice').textContent=t}function status(ok,t){$('statusDot').className='status-dot '+(ok===true?'ok':ok===false?'error':'');$('syncText').textContent=t}
function init(){const now=new Date();$('daySelect').value=now.toISOString().slice(0,10);$('monthSelect').value=now.toISOString().slice(0,7);for(let y=now.getFullYear()-5;y<=now.getFullYear()+2;y++)$('yearSelect').add(new Option(String(y),String(y)));$('yearSelect').value=String(now.getFullYear());$('quarterSelect').value=String(Math.ceil((now.getMonth()+1)/3));$('btnInput').href=APPS_SCRIPT_URL;bind();togglePeriodFields();reloadData(false)}
function bind(){$('periodType').addEventListener('change',()=>{togglePeriodFields();renderAll()});['daySelect','monthSelect','quarterSelect'].forEach(id=>$(id).addEventListener('change',renderAll));$('yearSelect').addEventListener('change',()=>reloadData(false));$('btnSync').addEventListener('click',()=>reloadData(true));$('btnExport').addEventListener('click',exportCsv);$('searchInput').addEventListener('input',renderLookup);$('historySearch').addEventListener('input',renderHistory);document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')}))}
function togglePeriodFields(){const t=$('periodType').value;$('dayField').hidden=t!=='day';$('monthField').hidden=t!=='month';$('quarterField').hidden=t!=='quarter';$('yearField').hidden=false}
function loadJsonp(year){return new Promise((resolve,reject)=>{if(!APPS_SCRIPT_URL.startsWith('https://script.google.com/'))return reject(new Error('Chưa dán URL Apps Script /exec vào app.js.'));const cb='cb_'+Date.now()+'_'+Math.floor(Math.random()*1e5);const s=document.createElement('script');let done=false;const clean=()=>{delete window[cb];s.remove()};const timer=setTimeout(()=>{if(done)return;done=true;clean();reject(new Error('Quá thời gian kết nối Apps Script.'))},20000);window[cb]=r=>{if(done)return;done=true;clearTimeout(timer);clean();r&&r.success?resolve(r):reject(new Error(r?.message||'Không tải được dữ liệu.'))};s.onerror=()=>{if(done)return;done=true;clearTimeout(timer);clean();reject(new Error('Không thể kết nối Apps Script.'))};s.src=APPS_SCRIPT_URL+'?'+new URLSearchParams({action:'data',year:String(year),callback:cb,_:String(Date.now())});document.body.appendChild(s)})}
async function reloadData(msg=true){state.year=Number($('yearSelect').value);showLoading(true);notice('');status(null,'Đang đồng bộ...');try{const r=await loadJsonp(state.year);state.categories=r.categories||[];state.records=r.records||[];state.logs=r.logs||[];state.generatedAt=r.generatedAt||'';renderAll();status(true,'Đã đồng bộ '+state.generatedAt);if(msg)toast('Đã đồng bộ dữ liệu.')}catch(e){status(false,'Đồng bộ thất bại');notice(e.message);toast(e.message,'error')}finally{showLoading(false)}}
function selectedRange(){const type=$('periodType').value;const year=Number($('yearSelect').value);if(type==='day'){const d=$('daySelect').value;return{type,label:'ngày '+formatDate(d),from:d,to:d}}if(type==='month'){const m=$('monthSelect').value||`${year}-01`;const [y,mo]=m.split('-').map(Number);const last=new Date(y,mo,0).getDate();return{type,label:`tháng ${mo}/${y}`,from:`${y}-${String(mo).padStart(2,'0')}-01`,to:`${y}-${String(mo).padStart(2,'0')}-${last}`}}if(type==='quarter'){const q=Number($('quarterSelect').value);const sm=(q-1)*3+1,em=q*3;const last=new Date(year,em,0).getDate();return{type,label:`quý ${q}/${year}`,from:`${year}-${String(sm).padStart(2,'0')}-01`,to:`${year}-${String(em).padStart(2,'0')}-${last}`}}return{type,label:`năm ${year}`,from:`${year}-01-01`,to:`${year}-12-31`}}
function filteredRecords(){const r=selectedRange();return state.records.filter(x=>x.date>=r.from&&x.date<=r.to)}function aggregate(records){const m=new Map();records.forEach(x=>m.set(x.code,(m.get(x.code)||0)+num(x.value)));return m}function displayCategories(){const a=[...state.categories];const pos=Math.max(a.findIndex(x=>x.code==='TAM_THAN_KHONG_BHYT')+1,0);a.splice(pos,0,{code:'TAM_THAN_TONG',name:'Khám tâm thần - Tổng cộng',group:'Tâm thần',unit:'Lượt',derived:true});return a}function getVal(map,code){if(code==='TAM_THAN_TONG')return num(map.get('TAM_THAN_BHYT'))+num(map.get('TAM_THAN_KHONG_BHYT'));return num(map.get(code))}
function renderAll(){renderDashboard();renderLookup();renderReport();renderHistory()}
function renderDashboard(){const range=selectedRange(),map=aggregate(filteredRecords());$('summaryTitle').textContent='Số liệu '+range.label;const featured=['NOI_TRU','NGOAI_TRU','CHUYEN_VIEN','KHAM_TONG_QUAT'];$('kpiGrid').innerHTML=featured.map(code=>{const c=state.categories.find(x=>x.code===code)||{name:code,unit:''};return `<article class="kpi"><div class="label">${esc(c.name)} <span class="unit">${esc(c.unit)}</span></div><div class="value">${fmt(getVal(map,code))}</div></article>`}).join('');const cats=displayCategories();$('summaryTable').innerHTML=`<table><thead><tr><th>Chỉ tiêu</th><th>Nhóm</th><th>Đơn vị</th><th>Giá trị</th></tr></thead><tbody>${cats.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.group)}</td><td>${esc(c.unit)}</td><td>${fmt(getVal(map,c.code))}</td></tr>`).join('')}</tbody></table>`}
function renderLookup(){const q=$('searchInput').value.trim().toLowerCase(),map=aggregate(filteredRecords());const rows=displayCategories().filter(c=>c.name.toLowerCase().includes(q));$('lookupTable').innerHTML=`<table><thead><tr><th>Chỉ tiêu</th><th>Nhóm</th><th>Đơn vị</th><th>${esc(selectedRange().label)}</th></tr></thead><tbody>${rows.length?rows.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.group)}</td><td>${esc(c.unit)}</td><td>${fmt(getVal(map,c.code))}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Không tìm thấy dữ liệu.</td></tr>'}</tbody></table>`}
function rangeMap(from,to){return aggregate(state.records.filter(x=>x.date>=from&&x.date<=to))}function renderReport(){const y=Number($('yearSelect').value),cats=displayCategories();const months=Array.from({length:12},(_,i)=>{const m=i+1,last=new Date(y,m,0).getDate();return rangeMap(`${y}-${String(m).padStart(2,'0')}-01`,`${y}-${String(m).padStart(2,'0')}-${last}`)});$('reportTable').innerHTML=`<table><thead><tr><th>Chỉ tiêu</th>${months.map((_,i)=>`<th>T${i+1}</th>`).join('')}<th>Cả năm</th></tr></thead><tbody>${cats.map(c=>`<tr><td>${esc(c.name)}</td>${months.map(m=>`<td>${fmt(getVal(m,c.code))}</td>`).join('')}<td>${fmt(months.reduce((s,m)=>s+getVal(m,c.code),0))}</td></tr>`).join('')}</tbody></table>`}
function renderHistory(){const range=selectedRange(),q=$('historySearch').value.trim().toLowerCase();const rows=state.logs.filter(x=>x.date>=range.from&&x.date<=range.to&&(x.name+' '+x.action+' '+x.content).toLowerCase().includes(q));$('historyList').innerHTML=rows.length?rows.map(x=>`<article class="history-item"><div><strong>${esc(formatDate(x.date))}</strong><small>${esc(x.updatedAt)}</small></div><div><strong>${esc(x.name||'Không rõ')}</strong><small>${esc(x.action)}</small></div><div>${esc(x.content)}</div></article>`).join(''):'<div class="empty">Không có nhật ký trong phạm vi đã chọn.</div>'}
function exportCsv(){const map=aggregate(filteredRecords()),range=selectedRange();const lines=[['Chỉ tiêu','Nhóm','Đơn vị',range.label],...displayCategories().map(c=>[c.name,c.group,c.unit,getVal(map,c.code)])];const csv='\ufeff'+lines.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`so-lieu-y-te-${range.type}-${range.from}-${range.to}.csv`;a.click();URL.revokeObjectURL(a.href)}function formatDate(s){if(!s)return'';const p=s.split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:s}document.addEventListener('DOMContentLoaded',init);
